database:
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  geospatial:
    database: <%= ENV['DATABASE_GEOSPATIAL_DATABASE'] %>
    schema:
      data: <%= ENV['DATABASE_GEOSPATIAL_SCHEMA_DATA'] %>
      metadata: <%= ENV['DATABASE_GEOSPATIAL_SCHEMA_METADATA'] %>
  tabular:
    database: <%= ENV['DATABASE_TABULAR_DATABASE'] %>
    schema:
      data: <%= ENV['DATABASE_TABULAR_SCHEMA_DATA'] %>
      metadata: <%= ENV['DATABASE_TABULAR_SCHEMA_METADATA'] %>
  town:
    database: <%= ENV['DATABASE_TOWN_DATABASE'] %>
    schema:
      data: <%= ENV['DATABASE_TOWN_SCHEMA_DATA'] %>
      metadata: <%= ENV['DATABASE_TOWN_SCHEMA_METADATA'] %>
carto:
  api_key: <%= ENV['CARTO_API_KEY'] %>
  url: <%= ENV['CARTO_URL'] %>
